# Generated by Django 3.1.4 on 2021-05-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fileupload_file_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='file_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
