# Generated by Django 3.1.4 on 2021-05-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fileupload_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='subject_code',
            field=models.CharField(default='IT', max_length=15),
            preserve_default=False,
        ),
    ]
