# Generated by Django 3.1.4 on 2021-05-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fileupload_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file_size',
            field=models.CharField(max_length=20),
        ),
    ]
