# Generated by Django 3.1.4 on 2021-05-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210503_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='documentType',
            field=models.CharField(choices=[('N', 'Notes'), ('P', 'PYQ'), ('G', 'Gate PYQ')], default='N', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileupload',
            name='subtitle',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
