# Generated by Django 3.1.3 on 2020-12-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='profession',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
