# Generated by Django 3.1.4 on 2021-05-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201207_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocViews',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('visit_id', models.IntegerField()),
            ],
        ),
    ]
